services:
  app:
    build:
      context: .
    volumes:
      - ./server:/app
    restart: always
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
  db:
    image: mysql:8
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    restart: always

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./server/static:/usr/share/nginx/html/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  redis:
    image: redis:alpine
    restart: always

  celery:
    build:
      context: .
    volumes:
      - ./server:/app
    restart: always
    env_file:
      - .env
    command: >
      sh -c "celery -A configs worker -l info -B"