# Generated by Django 4.1.4 on 2022-12-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carsphotomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
