# Generated by Django 4.1.4 on 2022-12-07 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_parks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_parks',
            },
        ),
    ]
