# Generated by Django 4.1.4 on 2022-12-08 20:45

import apps.users.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_is_active_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(upload_to=apps.users.services.upload_avatar),
        ),
    ]
