# Generated by Django 4.1.4 on 2022-12-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparksmodel',
            name='owner',
        ),
        migrations.CreateModel(
            name='AutoParksUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_parks.autoparksmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_parks_users',
            },
        ),
        migrations.AddField(
            model_name='autoparksmodel',
            name='owner',
            field=models.ManyToManyField(related_name='auto_parks', through='auto_parks.AutoParksUsersModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
